In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler 
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

In [2]:
dataset = load_diabetes()

In [3]:
#Create data frame for the given values
df = pd.DataFrame(dataset.data, columns=dataset.feature_names)
df

Adnan Sattikar 20MIC0124


age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [4]:
#This will tell us the total number of non null observations present including the total number of entries. Once number of entries isn’t equal to number of non null observations, we can begin to suspect missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB


In [5]:
#This will tell us the total number of NaN in or data.
df.isnull().sum()

age    0
sex    0
bmi    0
bp     0
s1     0
s2     0
s3     0
s4     0
s5     0
s6     0
dtype: int64

In [7]:
from sklearn.preprocessing import StandardScaler 
array = df.values
bparr = array[:,3:4]
print("BP array:\n",bparr)

BP array: Adnan Sattikar 20MIC0124
 [[ 2.18723855e-02]
 [-2.63275281e-02]
 [-5.67042229e-03]
 [-3.66560811e-02]
 [ 2.18723855e-02]
 [-1.94418262e-02]
 [-1.59989752e-02]
 [ 6.66294482e-02]
 [-4.00989321e-02]
 [-3.32132301e-02]
 [ 8.10098161e-03]
 [-3.32132301e-02]
 [-9.11327327e-03]
 [ 8.10098161e-03]
 [-1.25561242e-02]
 [ 8.04008521e-02]
 [ 4.94151933e-02]
 [ 5.63008953e-02]
 [-3.66560811e-02]
 [-4.00989321e-02]
 [-4.35417830e-02]
 [ 1.21527966e-03]
 [-9.11327327e-03]
 [ 3.10647976e-02]
 [-2.28846772e-02]
 [-4.00989321e-02]
 [-2.63275281e-02]
 [-4.00989321e-02]
 [-7.45274418e-02]
 [ 6.31865972e-02]
 [-1.94418262e-02]
 [-8.14131438e-02]
 [ 2.87580875e-02]
 [-2.22757132e-03]
 [-5.73131869e-02]
 [-4.92913442e-02]
 [ 5.28580443e-02]
 [-5.73131869e-02]
 [ 9.76151070e-02]
 [-7.45274418e-02]
 [ 2.18723855e-02]
 [-1.08955952e-01]
 [-1.48628344e-02]
 [-7.10845908e-02]
 [ 8.10098161e-03]
 [ 3.22009384e-02]
 [-3.32132301e-02]
 [-5.73131869e-02]
 [ 1.15438326e-02]
 [-5.67042229e-03]
 [ 1.49866836e

In [8]:
hdlarr = array[:,6:7]
print("HDL array: \n",hdlarr)

HDL array: 
 [[-0.04340085]
 [ 0.07441156]
 [-0.03235593]
 [-0.03603757]
 [ 0.00814208]
 [ 0.04127682]
 [ 0.00077881]
 [ 0.02286863]
 [-0.02867429]
 [-0.02499266]
 [-0.01394774]
 [-0.06549067]
 [ 0.04495846]
 [-0.00290283]
 [ 0.08177484]
 [-0.03971921]
 [ 0.07441156]
 [-0.03971921]
 [-0.02867429]
 [ 0.03759519]
 [ 0.00077881]
 [ 0.01550536]
 [ 0.02286863]
 [-0.05444576]
 [-0.00658447]
 [-0.0581274 ]
 [ 0.02655027]
 [ 0.01182372]
 [-0.00658447]
 [ 0.05232174]
 [ 0.02286863]
 [ 0.05968501]
 [-0.10230705]
 [ 0.11859122]
 [ 0.00814208]
 [ 0.13331777]
 [ 0.03759519]
 [ 0.03023191]
 [-0.02131102]
 [-0.01394774]
 [-0.02499266]
 [ 0.01550536]
 [-0.0581274 ]
 [ 0.11859122]
 [-0.07653559]
 [-0.01026611]
 [ 0.00446045]
 [-0.02499266]
 [ 0.04127682]
 [-0.07285395]
 [-0.00290283]
 [-0.02867429]
 [ 0.02655027]
 [ 0.01550536]
 [ 0.05232174]
 [ 0.08545648]
 [-0.03603757]
 [ 0.05232174]
 [ 0.18117906]
 [ 0.03023191]
 [ 0.05232174]
 [-0.08021722]
 [ 0.05968501]
 [-0.01394774]
 [-0.00290283]
 [-0.0544457

In [9]:
scaler = StandardScaler()
rescaledBP = scaler.fit_transform(bparr) 
np.set_printoptions(precision=2) 
print("Rescaled BP: \n",rescaledBP[0:,:])

20MIC0124 Adnan Sattikar Machine Learning Lab Mid Term Rescaled BP: 
 [[ 4.60e-01]
 [-5.54e-01]
 [-1.19e-01]
 [-7.71e-01]
 [ 4.60e-01]
 [-4.09e-01]
 [-3.36e-01]
 [ 1.40e+00]
 [-8.43e-01]
 [-6.98e-01]
 [ 1.70e-01]
 [-6.98e-01]
 [-1.92e-01]
 [ 1.70e-01]
 [-2.64e-01]
 [ 1.69e+00]
 [ 1.04e+00]
 [ 1.18e+00]
 [-7.71e-01]
 [-8.43e-01]
 [-9.15e-01]
 [ 2.55e-02]
 [-1.92e-01]
 [ 6.53e-01]
 [-4.81e-01]
 [-8.43e-01]
 [-5.54e-01]
 [-8.43e-01]
 [-1.57e+00]
 [ 1.33e+00]
 [-4.09e-01]
 [-1.71e+00]
 [ 6.05e-01]
 [-4.68e-02]
 [-1.20e+00]
 [-1.04e+00]
 [ 1.11e+00]
 [-1.20e+00]
 [ 2.05e+00]
 [-1.57e+00]
 [ 4.60e-01]
 [-2.29e+00]
 [-3.12e-01]
 [-1.49e+00]
 [ 1.70e-01]
 [ 6.77e-01]
 [-6.98e-01]
 [-1.20e+00]
 [ 2.43e-01]
 [-1.19e-01]
 [ 3.15e-01]
 [ 6.05e-01]
 [-1.19e-01]
 [ 1.47e+00]
 [ 1.70e-01]
 [-7.71e-01]
 [-5.54e-01]
 [-1.06e+00]
 [ 7.49e-01]
 [ 2.43e-01]
 [-8.43e-01]
 [-1.13e+00]
 [-8.43e-01]
 [-1.28e+00]
 [-8.43e-01]
 [ 1.26e+00]
 [-6.98e-01]
 [-3.60e-01]
 [-8.43e-01]
 [-1.19e-01]
 [-2.64e-01]
 [ 2.63

In [10]:
rescaledhdl = scaler.fit_transform(hdlarr) 
np.set_printoptions(precision=2) 
print("Rescaled HDL:\n",rescaledhdl[0:,:])

Rescaled HDL:
 [[-0.91]
 [ 1.56]
 [-0.68]
 [-0.76]
 [ 0.17]
 [ 0.87]
 [ 0.02]
 [ 0.48]
 [-0.6 ]
 [-0.53]
 [-0.29]
 [-1.38]
 [ 0.95]
 [-0.06]
 [ 1.72]
 [-0.84]
 [ 1.56]
 [-0.84]
 [-0.6 ]
 [ 0.79]
 [ 0.02]
 [ 0.33]
 [ 0.48]
 [-1.14]
 [-0.14]
 [-1.22]
 [ 0.56]
 [ 0.25]
 [-0.14]
 [ 1.1 ]
 [ 0.48]
 [ 1.25]
 [-2.15]
 [ 2.49]
 [ 0.17]
 [ 2.8 ]
 [ 0.79]
 [ 0.64]
 [-0.45]
 [-0.29]
 [-0.53]
 [ 0.33]
 [-1.22]
 [ 2.49]
 [-1.61]
 [-0.22]
 [ 0.09]
 [-0.53]
 [ 0.87]
 [-1.53]
 [-0.06]
 [-0.6 ]
 [ 0.56]
 [ 0.33]
 [ 1.1 ]
 [ 1.8 ]
 [-0.76]
 [ 1.1 ]
 [ 3.81]
 [ 0.64]
 [ 1.1 ]
 [-1.69]
 [ 1.25]
 [-0.29]
 [-0.06]
 [-1.14]
 [-1.53]
 [-0.29]
 [-0.22]
 [-0.29]
 [ 1.49]
 [-0.22]
 [ 1.18]
 [-0.14]
 [ 0.87]
 [-0.45]
 [-1.14]
 [ 0.33]
 [-1.14]
 [ 0.25]
 [ 1.1 ]
 [-0.45]
 [ 2.11]
 [-0.22]
 [ 0.95]
 [ 0.33]
 [-0.84]
 [ 2.03]
 [ 0.79]
 [ 1.41]
 [ 1.64]
 [-0.22]
 [ 1.33]
 [ 1.33]
 [ 1.49]
 [-0.91]
 [-0.91]
 [-0.68]
 [ 0.17]
 [-0.29]
 [ 0.64]
 [ 1.33]
 [ 1.18]
 [-0.76]
 [ 0.48]
 [-0.29]
 [ 0.17]
 [-1.22]
 [-1.53]
 [-1

In [11]:
x_train, x_test, y_train, y_test = train_test_split(rescaledBP,rescaledhdl,test_size=0.3,random_state=42)
print("BP test:\n",x_test)

BP test:
 [[-0.34]
 [ 0.46]
 [-0.26]
 [ 1.67]
 [-0.05]
 [-0.55]
 [ 0.32]
 [ 0.46]
 [-1.2 ]
 [-0.41]
 [-0.48]
 [-0.48]
 [-0.55]
 [ 1.33]
 [-0.05]
 [-0.12]
 [ 0.17]
 [ 1.47]
 [ 1.47]
 [ 1.47]
 [-0.7 ]
 [-1.13]
 [-0.77]
 [ 1.04]
 [-0.41]
 [ 0.89]
 [ 1.18]
 [ 1.4 ]
 [-1.06]
 [-0.19]
 [-1.11]
 [-0.55]
 [-1.57]
 [ 0.6 ]
 [-1.2 ]
 [ 1.11]
 [-0.55]
 [-0.38]
 [ 0.1 ]
 [-1.2 ]
 [-0.26]
 [ 1.21]
 [ 0.6 ]
 [-0.48]
 [ 0.73]
 [-0.55]
 [-1.57]
 [-0.05]
 [-0.55]
 [-0.63]
 [-0.92]
 [-1.42]
 [-0.7 ]
 [-0.34]
 [ 1.69]
 [-0.05]
 [-0.7 ]
 [ 0.46]
 [-0.84]
 [-1.64]
 [-0.12]
 [-0.55]
 [-0.41]
 [ 1.33]
 [-0.84]
 [ 1.33]
 [ 1.18]
 [ 1.18]
 [-1.42]
 [-0.84]
 [ 0.17]
 [ 1.11]
 [ 1.84]
 [-0.31]
 [-0.84]
 [ 0.6 ]
 [ 1.04]
 [ 0.03]
 [ 0.82]
 [-0.34]
 [-0.19]
 [-0.7 ]
 [-2.15]
 [-0.63]
 [-0.12]
 [-0.84]
 [-1.06]
 [-1.35]
 [-0.48]
 [ 1.18]
 [-0.7 ]
 [ 2.05]
 [-0.63]
 [-1.71]
 [-2.12]
 [ 0.46]
 [ 1.26]
 [-0.84]
 [-0.26]
 [-1.45]
 [ 1.26]
 [-0.92]
 [ 1.62]
 [-0.12]
 [-0.12]
 [-0.41]
 [ 0.68]
 [ 1.33]
 [-0.26]
 [ 1.23]


In [12]:
print("HDL test:\n",y_test)

HDL test:
 [[ 0.4 ]
 [ 0.02]
 [ 1.18]
 [-1.61]
 [-0.14]
 [ 1.49]
 [-0.45]
 [ 0.02]
 [-0.14]
 [ 0.4 ]
 [ 1.18]
 [-1.14]
 [ 0.87]
 [-0.99]
 [ 0.4 ]
 [-0.14]
 [-0.37]
 [-1.07]
 [-1.14]
 [-0.45]
 [-0.53]
 [ 0.71]
 [ 1.8 ]
 [-0.29]
 [ 0.48]
 [-0.91]
 [-0.68]
 [-1.61]
 [ 1.95]
 [ 0.02]
 [-0.6 ]
 [ 0.25]
 [-0.29]
 [-1.22]
 [-0.45]
 [ 0.56]
 [-0.45]
 [-0.29]
 [-0.6 ]
 [ 1.56]
 [ 1.49]
 [ 1.56]
 [-1.3 ]
 [-1.3 ]
 [ 0.79]
 [ 2.11]
 [ 0.33]
 [ 2.49]
 [ 0.87]
 [ 0.25]
 [ 0.4 ]
 [ 0.33]
 [-1.38]
 [ 1.1 ]
 [-0.84]
 [ 0.48]
 [ 0.79]
 [-0.91]
 [ 0.79]
 [ 2.96]
 [-0.37]
 [-0.76]
 [ 0.48]
 [ 1.33]
 [-0.91]
 [ 0.17]
 [-0.84]
 [-0.45]
 [ 0.17]
 [-1.22]
 [-1.38]
 [-0.84]
 [-0.99]
 [-1.22]
 [ 0.71]
 [-1.53]
 [-0.06]
 [-0.6 ]
 [ 0.17]
 [-1.61]
 [ 0.48]
 [ 0.09]
 [ 1.33]
 [ 2.57]
 [ 0.87]
 [ 1.64]
 [ 1.1 ]
 [ 0.4 ]
 [-0.14]
 [-0.84]
 [-1.53]
 [-0.14]
 [ 0.64]
 [ 1.25]
 [ 0.95]
 [-0.14]
 [-0.99]
 [-0.91]
 [ 1.49]
 [ 0.95]
 [-0.6 ]
 [-2.07]
 [-1.22]
 [-0.22]
 [-0.06]
 [ 0.87]
 [-0.22]
 [-0.29]
 [ 1.33]
 [-0.29]

In [16]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler 
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor

x_train, x_test, y_train, y_test = train_test_split(rescaledBP,rescaledhdl,test_size=0.3,random_state=42)

In [17]:
mlp = MLPRegressor(hidden_layer_sizes=(10,10,10), activation='relu', max_iter=1000)
mlp.fit(x_train,y_train)

predict_train = mlp.predict(x_train)
predict_test = mlp.predict(x_test)

print("Predict train: \n",predict_train)
print("Predict test: \n",predict_test)

c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1607: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Adnan Sattikar 20MIC0124
Predict train: 
 [-0.27 -0.32 -0.17 -0.32  0.09  0.29 -0.2   0.08 -0.22  0.02  0.08  0.08
 -0.07 -0.14  0.16  0.14 -0.01 -0.09 -0.32 -0.09 -0.28  0.05 -0.22  0.08
 -0.04 -0.28 -0.29 -0.25  0.08  0.05  0.02  0.13  0.05 -0.    0.1   0.08
  0.08 -0.07  0.21  0.08 -0.28 -0.28 -0.27  0.1  -0.28 -0.24 -0.07  0.08
 -0.2  -0.04  0.09  0.08  0.07  0.18 -0.17  0.08  0.08 -0.04  0.21 -0.07
  0.08  0.09  0.   -0.23  0.04 -0.14  0.08  0.18 -0.19  0.05 -0.22  0.09
 -0.28 -0.19  0.07  0.09  0.05  0.09  0.08  0.05  0.21  0.02  0.39 -0.27
  0.07  0.09 -0.29  0.09  0.08  0.1   0.07 -0.21  0.11  0.09 -0.14 -0.04
 -0.22 -0.29  0.09 -0.26 -0.28  0.09 -0.22 -0.02 -0.2  -0.31  0.02  0.
  0.08 -0.07  0.14  0.12  0.07 -0.27  0.09 -0.02 -0.05 -0.09  0.07  0.08
 -0.32  0.05  0.09  0.05 -0.29  0.08  0.09 -0.25  0.09 -0.17  0.27 -0.17
  0.09 -0.22 -0.14  0.11 -0.28  0.07  0.09  0.05 -0.07  0.13  0.09  0.14
  0.09  0.09  0.1   0.02  0.07 -0.31 -0.04  0.29 -0.31  0.08  0.    0.08
  0.09 -0.0

In [18]:
from sklearn.metrics import mean_absolute_error
print("Mean absolute error for training samples ",mean_absolute_error(predict_train,y_train))
print("Mean absolute error for testing samples ",mean_absolute_error(predict_test, y_test))

Mean absolute error for training samples  0.7529473744702393
Mean absolute error for testing samples  0.7865014032872498


In [19]:
from sklearn.metrics import mean_squared_error
print("Mean squared error for training samples ",mean_squared_error(predict_train,y_train))
print("Mean squared error for testing samples ",mean_squared_error(predict_test, y_test))

Mean squared error for training samples  0.9546008281348414
Mean squared error for testing samples  0.9452076921968656


In [20]:
from sklearn.metrics import r2_score
print("r2 score for training samples",r2_score(predict_train,y_train))
print("r2 score for testing samples",r2_score(predict_test, y_test))

r2 score for training samples -37.286606902149835
r2 score for testing samples -32.8990211141563


In [21]:
x_train, x_test, y_train, y_test = train_test_split(rescaledBP,rescaledhdl,test_size=0.50,random_state=42)
mlp = MLPRegressor(hidden_layer_sizes=(10,10,10), activation='relu', max_iter=1000)
mlp.fit(x_train,y_train)
predict_train = mlp.predict(x_train)
predict_test = mlp.predict(x_test)

c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1607: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [22]:
from sklearn.metrics import mean_absolute_error
print("Mean absolute error for training samples ",mean_absolute_error(predict_train,y_train))
print("Mean absolute error for testing samples ",mean_absolute_error(predict_test, y_test))
from sklearn.metrics import mean_squared_error
print("Mean squared error for training samples ",mean_squared_error(predict_train,y_train))
print("Mean squared error for testing samples ",mean_squared_error(predict_test, y_test))
from sklearn.metrics import r2_score
print("r2 score for training samples",r2_score(predict_train,y_train))
print("r2 score for testing samples",r2_score(predict_test, y_test))

Mean absolute error for training samples  0.7786924365571825
Mean absolute error for testing samples  0.7736004453846547
Mean squared error for training samples  1.0140401257801852
Mean squared error for testing samples  0.9197977682787534
r2 score for training samples -31.82549936095471
r2 score for testing samples -29.638265952071233


In [23]:
x_train, x_test, y_train, y_test = train_test_split(rescaledBP,rescaledhdl,test_size=0.75,random_state=42)
mlp = MLPRegressor(hidden_layer_sizes=(10,10,10), activation='relu',max_iter=1000)
mlp.fit(x_train,y_train)
predict_train = mlp.predict(x_train)
predict_test = mlp.predict(x_test)

c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1607: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [24]:
from sklearn.metrics import mean_absolute_error
print("Mean absolute error for training samples ",mean_absolute_error(predict_train,y_train))
print("Mean absolute error for testing samples ",mean_absolute_error(predict_test, y_test))
from sklearn.metrics import mean_squared_error
print("Mean squared error for training samples ",mean_squared_error(predict_train,y_train))
print("Mean squared error for testing samples ",mean_squared_error(predict_test, y_test))
from sklearn.metrics import r2_score
print("r2 score for training samples",r2_score(predict_train,y_train))
print("r2 score for testing samples",r2_score(predict_test, y_test))

Mean absolute error for training samples  0.7445598563208751
Mean absolute error for testing samples  0.8468949093357337
Mean squared error for training samples  0.9297458056467313
Mean squared error for testing samples  1.0900236688007257
r2 score for training samples -5.752192553058887
r2 score for testing samples -4.898403147742305


The most optimal sample is the 50% testing samples where the errors are minimum when compared to 30% and 75% 
samples. 